-- MySQL Script generated by MySQL Workbench
-- Wed Feb 27 23:17:00 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `idPersona` INT NOT NULL,
  `pNombre` VARCHAR(45) NULL,
  `sNombre` VARCHAR(45) NULL,
  `pApellido` VARCHAR(45) NULL,
  `sApellido` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `correoElectronico` VARCHAR(45) NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefono` (
  `idTelefono` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idTelefono`),
  INDEX `fk_Telefono_Persona_idx` (`Persona_idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_Telefono_Persona`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `fechaRegistro` DATE NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Cliente_Persona1_idx` (`Persona_idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoReferencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoReferencia` (
  `idTipoReferencia` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoReferencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Referencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Referencia` (
  `idReferencia` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `TipoReferencia_idTipoReferencia` INT NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idReferencia`),
  INDEX `fk_Referencia_TipoReferencia1_idx` (`TipoReferencia_idTipoReferencia` ASC) VISIBLE,
  INDEX `fk_Referencia_Persona1_idx` (`Persona_idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_Referencia_TipoReferencia1`
    FOREIGN KEY (`TipoReferencia_idTipoReferencia`)
    REFERENCES `mydb`.`TipoReferencia` (`idTipoReferencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Referencia_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente_has_Referencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente_has_Referencia` (
  `Cliente_idCliente` INT NOT NULL,
  `Referencia_idReferencia` INT NOT NULL,
  PRIMARY KEY (`Cliente_idCliente`, `Referencia_idReferencia`),
  INDEX `fk_Cliente_has_Referencia_Referencia1_idx` (`Referencia_idReferencia` ASC) VISIBLE,
  INDEX `fk_Cliente_has_Referencia_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_has_Referencia_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Referencia_Referencia1`
    FOREIGN KEY (`Referencia_idReferencia`)
    REFERENCES `mydb`.`Referencia` (`idReferencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Banco` (
  `idBanco` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `ubicacion` VARCHAR(45) NULL,
  PRIMARY KEY (`idBanco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoPrestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoPrestamo` (
  `idTipoPrestamo` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoPrestamo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prestamo` (
  `idPrestamo` INT NOT NULL,
  `cantidadPagos` INT NULL,
  `montoCuotas` DOUBLE NULL,
  `Banco_idBanco` INT NOT NULL,
  `TipoPrestamo_idTipoPrestamo` INT NOT NULL,
  PRIMARY KEY (`idPrestamo`),
  INDEX `fk_Prestamo_Banco1_idx` (`Banco_idBanco` ASC) VISIBLE,
  INDEX `fk_Prestamo_TipoPrestamo1_idx` (`TipoPrestamo_idTipoPrestamo` ASC) VISIBLE,
  CONSTRAINT `fk_Prestamo_Banco1`
    FOREIGN KEY (`Banco_idBanco`)
    REFERENCES `mydb`.`Banco` (`idBanco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestamo_TipoPrestamo1`
    FOREIGN KEY (`TipoPrestamo_idTipoPrestamo`)
    REFERENCES `mydb`.`TipoPrestamo` (`idTipoPrestamo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Banco_has_Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Banco_has_Cliente` (
  `Banco_idBanco` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`Banco_idBanco`, `Cliente_idCliente`),
  INDEX `fk_Banco_has_Cliente_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Banco_has_Cliente_Banco1_idx` (`Banco_idBanco` ASC) VISIBLE,
  CONSTRAINT `fk_Banco_has_Cliente_Banco1`
    FOREIGN KEY (`Banco_idBanco`)
    REFERENCES `mydb`.`Banco` (`idBanco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Banco_has_Cliente_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RequisitosEtapaPrestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RequisitosEtapaPrestamo` (
  `idRequisitos` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idRequisitos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EstadoPrestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EstadoPrestamo` (
  `idEstadoPrestamo` INT NOT NULL,
  `pagosRealizados` INT NULL,
  `Prestamo_idPrestamo` INT NOT NULL,
  PRIMARY KEY (`idEstadoPrestamo`),
  INDEX `fk_EstadoPrestamo_Prestamo1_idx` (`Prestamo_idPrestamo` ASC) VISIBLE,
  CONSTRAINT `fk_EstadoPrestamo_Prestamo1`
    FOREIGN KEY (`Prestamo_idPrestamo`)
    REFERENCES `mydb`.`Prestamo` (`idPrestamo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CuentaCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CuentaCliente` (
  `idCuentaCliente` INT NOT NULL,
  `saldo` DATE NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idCuentaCliente`),
  INDEX `fk_CuentaCliente_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_CuentaCliente_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CuentaCliente_has_Prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CuentaCliente_has_Prestamo` (
  `CuentaCliente_idCuentaCliente` INT NOT NULL,
  `Prestamo_idPrestamo` INT NOT NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`CuentaCliente_idCuentaCliente`, `Prestamo_idPrestamo`),
  INDEX `fk_CuentaCliente_has_Prestamo_Prestamo1_idx` (`Prestamo_idPrestamo` ASC) VISIBLE,
  INDEX `fk_CuentaCliente_has_Prestamo_CuentaCliente1_idx` (`CuentaCliente_idCuentaCliente` ASC) VISIBLE,
  CONSTRAINT `fk_CuentaCliente_has_Prestamo_CuentaCliente1`
    FOREIGN KEY (`CuentaCliente_idCuentaCliente`)
    REFERENCES `mydb`.`CuentaCliente` (`idCuentaCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CuentaCliente_has_Prestamo_Prestamo1`
    FOREIGN KEY (`Prestamo_idPrestamo`)
    REFERENCES `mydb`.`Prestamo` (`idPrestamo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleado` (
  `idempleado` INT NOT NULL,
  `cargo` VARCHAR(45) NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idempleado`),
  INDEX `fk_empleado_Persona1_idx` (`Persona_idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_empleado_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleado_has_Banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleado_has_Banco` (
  `empleado_idempleado` INT NOT NULL,
  `Banco_idBanco` INT NOT NULL,
  PRIMARY KEY (`empleado_idempleado`, `Banco_idBanco`),
  INDEX `fk_empleado_has_Banco_Banco1_idx` (`Banco_idBanco` ASC) VISIBLE,
  INDEX `fk_empleado_has_Banco_empleado1_idx` (`empleado_idempleado` ASC) VISIBLE,
  CONSTRAINT `fk_empleado_has_Banco_empleado1`
    FOREIGN KEY (`empleado_idempleado`)
    REFERENCES `mydb`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_has_Banco_Banco1`
    FOREIGN KEY (`Banco_idBanco`)
    REFERENCES `mydb`.`Banco` (`idBanco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Banco_has_CuentaCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Banco_has_CuentaCliente` (
  `Banco_idBanco` INT NOT NULL,
  `CuentaCliente_idCuentaCliente` INT NOT NULL,
  PRIMARY KEY (`Banco_idBanco`, `CuentaCliente_idCuentaCliente`),
  INDEX `fk_Banco_has_CuentaCliente_CuentaCliente1_idx` (`CuentaCliente_idCuentaCliente` ASC) VISIBLE,
  INDEX `fk_Banco_has_CuentaCliente_Banco1_idx` (`Banco_idBanco` ASC) VISIBLE,
  CONSTRAINT `fk_Banco_has_CuentaCliente_Banco1`
    FOREIGN KEY (`Banco_idBanco`)
    REFERENCES `mydb`.`Banco` (`idBanco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Banco_has_CuentaCliente_CuentaCliente1`
    FOREIGN KEY (`CuentaCliente_idCuentaCliente`)
    REFERENCES `mydb`.`CuentaCliente` (`idCuentaCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SolicitudEtapaPrestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SolicitudEtapaPrestamo` (
  `idSolicitudEtapaPrestamo` INT NOT NULL,
  `descripcionEtapa` VARCHAR(45) NULL,
  `fechaSolicitud` DATE NULL,
  `fechaAprobacion` VARCHAR(45) NULL,
  `Prestamo_idPrestamo` INT NOT NULL,
  `empleado_idempleado` INT NOT NULL,
  PRIMARY KEY (`idSolicitudEtapaPrestamo`),
  INDEX `fk_Solicitud_Prestamo1_idx` (`Prestamo_idPrestamo` ASC) VISIBLE,
  INDEX `fk_Solicitud_empleado1_idx` (`empleado_idempleado` ASC) VISIBLE,
  CONSTRAINT `fk_Solicitud_Prestamo1`
    FOREIGN KEY (`Prestamo_idPrestamo`)
    REFERENCES `mydb`.`Prestamo` (`idPrestamo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Solicitud_empleado1`
    FOREIGN KEY (`empleado_idempleado`)
    REFERENCES `mydb`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente_has_SolicitudPrestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente_has_SolicitudPrestamo` (
  `Cliente_idCliente` INT NOT NULL,
  `SolicitudPrestamo_idSolicitud` INT NOT NULL,
  PRIMARY KEY (`Cliente_idCliente`, `SolicitudPrestamo_idSolicitud`),
  INDEX `fk_Cliente_has_SolicitudPrestamo_SolicitudPrestamo1_idx` (`SolicitudPrestamo_idSolicitud` ASC) VISIBLE,
  INDEX `fk_Cliente_has_SolicitudPrestamo_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_has_SolicitudPrestamo_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_SolicitudPrestamo_SolicitudPrestamo1`
    FOREIGN KEY (`SolicitudPrestamo_idSolicitud`)
    REFERENCES `mydb`.`SolicitudEtapaPrestamo` (`idSolicitudEtapaPrestamo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PlanAmortizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PlanAmortizacion` (
  `idPlanAmortizacion` INT NOT NULL,
  `fechaPago` DATE NULL,
  `montoCapital` DOUBLE NULL,
  `intereses` DOUBLE NULL,
  `totalPagos` INT NULL,
  `Prestamo_idPrestamo` INT NOT NULL,
  PRIMARY KEY (`idPlanAmortizacion`),
  INDEX `fk_PlanAmortizacion_Prestamo1_idx` (`Prestamo_idPrestamo` ASC) VISIBLE,
  CONSTRAINT `fk_PlanAmortizacion_Prestamo1`
    FOREIGN KEY (`Prestamo_idPrestamo`)
    REFERENCES `mydb`.`Prestamo` (`idPrestamo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RequisitosEtapaPrestamo_has_SolicitudEtapaPrestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RequisitosEtapaPrestamo_has_SolicitudEtapaPrestamo` (
  `RequisitosEtapaPrestamo_idRequisitos` INT NOT NULL,
  `SolicitudEtapaPrestamo_idSolicitudEtapaPrestamo` INT NOT NULL,
  `estado` VARCHAR(45) NULL,
  `fecha_hora_inicio` DATETIME NULL,
  `fecha_hora_fin` DATETIME NULL,
  PRIMARY KEY (`RequisitosEtapaPrestamo_idRequisitos`, `SolicitudEtapaPrestamo_idSolicitudEtapaPrestamo`),
  INDEX `fk_RequisitosEtapaPrestamo_has_SolicitudEtapaPrestamo_Solic_idx` (`SolicitudEtapaPrestamo_idSolicitudEtapaPrestamo` ASC) VISIBLE,
  INDEX `fk_RequisitosEtapaPrestamo_has_SolicitudEtapaPrestamo_Requi_idx` (`RequisitosEtapaPrestamo_idRequisitos` ASC) VISIBLE,
  CONSTRAINT `fk_RequisitosEtapaPrestamo_has_SolicitudEtapaPrestamo_Requisi1`
    FOREIGN KEY (`RequisitosEtapaPrestamo_idRequisitos`)
    REFERENCES `mydb`.`RequisitosEtapaPrestamo` (`idRequisitos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RequisitosEtapaPrestamo_has_SolicitudEtapaPrestamo_Solicit1`
    FOREIGN KEY (`SolicitudEtapaPrestamo_idSolicitudEtapaPrestamo`)
    REFERENCES `mydb`.`SolicitudEtapaPrestamo` (`idSolicitudEtapaPrestamo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
