-- MySQL Script generated by MySQL Workbench
-- Thu Mar 28 08:38:03 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefono` (
  `idTelefono` INT NOT NULL,
  `numeroTelefono` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idTelefono`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `idPersona` INT NOT NULL,
  `noIdentidad` VARCHAR(45) NULL,
  `pnombre` VARCHAR(45) NULL,
  `snombre` VARCHAR(45) NULL,
  `papellido` VARCHAR(45) NULL,
  `sapellido` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `correoElectronico` VARCHAR(45) NULL,
  `Telefono_idTelefono` INT NOT NULL,
  PRIMARY KEY (`idPersona`),
  INDEX `fk_Persona_Telefono1_idx` (`Telefono_idTelefono` ASC),
  CONSTRAINT `fk_Persona_Telefono1`
    FOREIGN KEY (`Telefono_idTelefono`)
    REFERENCES `mydb`.`Telefono` (`idTelefono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estudiante` (
  `numeroCuenta` VARCHAR(45) NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`numeroCuenta`),
  INDEX `fk_Estudiante_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_Estudiante_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Profesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Profesores` (
  `idProfesores` INT NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idProfesores`),
  INDEX `fk_Profesores_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_Profesores_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PeriodoAcademico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PeriodoAcademico` (
  `idPeriodoAcademico` INT NOT NULL,
  `fechaInicio` DATE NULL,
  `fechaFin` DATE NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idPeriodoAcademico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Asignatura` (
  `idAsignatura` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `codigo` VARCHAR(45) NULL,
  `creditosAcademicos` INT NULL,
  PRIMARY KEY (`idAsignatura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Edificio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Edificio` (
  `idEdificio` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idEdificio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aula` (
  `idAula` INT NOT NULL,
  `numero` VARCHAR(45) NULL,
  `Edificio_idEdificio` INT NOT NULL,
  PRIMARY KEY (`idAula`),
  INDEX `fk_Aula_Edificio1_idx` (`Edificio_idEdificio` ASC),
  CONSTRAINT `fk_Aula_Edificio1`
    FOREIGN KEY (`Edificio_idEdificio`)
    REFERENCES `mydb`.`Edificio` (`idEdificio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Seccion` (
  `idSeccion` INT NOT NULL,
  `seccion` VARCHAR(45) NULL,
  `horaInicio` TIME NULL,
  `horaFin` TIME NULL,
  `Asignatura_idAsignatura` INT NOT NULL,
  `Profesores_idProfesores` INT NOT NULL,
  `PeriodoAcademico_idPeriodoAcademico` INT NOT NULL,
  `Aula_idAula` INT NOT NULL,
  `cuposMaximo` INT NULL,
  PRIMARY KEY (`idSeccion`),
  INDEX `fk_Seccion_Asignatura1_idx` (`Asignatura_idAsignatura` ASC),
  INDEX `fk_Seccion_Profesores1_idx` (`Profesores_idProfesores` ASC),
  INDEX `fk_Seccion_PeriodoAcademico1_idx` (`PeriodoAcademico_idPeriodoAcademico` ASC),
  INDEX `fk_Seccion_Aula1_idx` (`Aula_idAula` ASC),
  CONSTRAINT `fk_Seccion_Asignatura1`
    FOREIGN KEY (`Asignatura_idAsignatura`)
    REFERENCES `mydb`.`Asignatura` (`idAsignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Seccion_Profesores1`
    FOREIGN KEY (`Profesores_idProfesores`)
    REFERENCES `mydb`.`Profesores` (`idProfesores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Seccion_PeriodoAcademico1`
    FOREIGN KEY (`PeriodoAcademico_idPeriodoAcademico`)
    REFERENCES `mydb`.`PeriodoAcademico` (`idPeriodoAcademico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Seccion_Aula1`
    FOREIGN KEY (`Aula_idAula`)
    REFERENCES `mydb`.`Aula` (`idAula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carrera` (
  `idCarrera` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `fechaInicio` DATE NULL,
  PRIMARY KEY (`idCarrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PlanEstudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PlanEstudio` (
  `idPlanEstudio` INT NOT NULL,
  `fechaAprobacion` DATE NULL,
  `fechaFin` DATE NULL,
  `numeroAcuerdo` VARCHAR(45) NULL,
  `Carrera_idCarrera` INT NOT NULL,
  PRIMARY KEY (`idPlanEstudio`),
  INDEX `fk_PlanEstudio_Carrera1_idx` (`Carrera_idCarrera` ASC),
  CONSTRAINT `fk_PlanEstudio_Carrera1`
    FOREIGN KEY (`Carrera_idCarrera`)
    REFERENCES `mydb`.`Carrera` (`idCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Asignatura_has_PlanEstudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Asignatura_has_PlanEstudio` (
  `Asignatura_idAsignatura` INT NOT NULL,
  `PlanEstudio_idPlanEstudio` INT NOT NULL,
  PRIMARY KEY (`Asignatura_idAsignatura`, `PlanEstudio_idPlanEstudio`),
  INDEX `fk_Asignatura_has_PlanEstudio_PlanEstudio1_idx` (`PlanEstudio_idPlanEstudio` ASC),
  INDEX `fk_Asignatura_has_PlanEstudio_Asignatura1_idx` (`Asignatura_idAsignatura` ASC),
  CONSTRAINT `fk_Asignatura_has_PlanEstudio_Asignatura1`
    FOREIGN KEY (`Asignatura_idAsignatura`)
    REFERENCES `mydb`.`Asignatura` (`idAsignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asignatura_has_PlanEstudio_PlanEstudio1`
    FOREIGN KEY (`PlanEstudio_idPlanEstudio`)
    REFERENCES `mydb`.`PlanEstudio` (`idPlanEstudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AsignaturaPlanEstudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AsignaturaPlanEstudio` (
  `idAsignaturaPlanEstudio` INT NOT NULL,
  `Asignatura_idAsignatura` INT NOT NULL,
  `PlanEstudio_idPlanEstudio` INT NOT NULL,
  PRIMARY KEY (`idAsignaturaPlanEstudio`),
  INDEX `fk_AsignaturaPlanEstudio_Asignatura1_idx` (`Asignatura_idAsignatura` ASC),
  INDEX `fk_AsignaturaPlanEstudio_PlanEstudio1_idx` (`PlanEstudio_idPlanEstudio` ASC),
  CONSTRAINT `fk_AsignaturaPlanEstudio_Asignatura1`
    FOREIGN KEY (`Asignatura_idAsignatura`)
    REFERENCES `mydb`.`Asignatura` (`idAsignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AsignaturaPlanEstudio_PlanEstudio1`
    FOREIGN KEY (`PlanEstudio_idPlanEstudio`)
    REFERENCES `mydb`.`PlanEstudio` (`idPlanEstudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Requisito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Requisito` (
  `idRequisito` INT NOT NULL,
  `idAsignatura` INT NOT NULL,
  `PlanEstudio_idPlanEstudio` INT NOT NULL,
  `idAsignaturaRequisitos` INT NOT NULL,
  PRIMARY KEY (`idRequisito`),
  INDEX `fk_Requisito_Asignatura1_idx` (`idAsignatura` ASC),
  INDEX `fk_Requisito_PlanEstudio1_idx` (`PlanEstudio_idPlanEstudio` ASC),
  INDEX `fk_Requisito_Asignatura2_idx` (`idAsignaturaRequisitos` ASC),
  CONSTRAINT `fk_Requisito_Asignatura1`
    FOREIGN KEY (`idAsignatura`)
    REFERENCES `mydb`.`Asignatura` (`idAsignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Requisito_PlanEstudio1`
    FOREIGN KEY (`PlanEstudio_idPlanEstudio`)
    REFERENCES `mydb`.`PlanEstudio` (`idPlanEstudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Requisito_Asignatura2`
    FOREIGN KEY (`idAsignaturaRequisitos`)
    REFERENCES `mydb`.`Asignatura` (`idAsignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Requisitos2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Requisitos2` (
  `idRequisitos2` INT NOT NULL,
  `idAsignaturaPlanEstudio` INT NOT NULL,
  `idPlanEstudioAsignatura` INT NOT NULL,
  `iidAsignaturaPlanEstudioRequisito` INT NOT NULL,
  `idPlanEstudioRequisito` INT NOT NULL,
  PRIMARY KEY (`idRequisitos2`),
  INDEX `fk_Requisitos2_Asignatura_has_PlanEstudio1_idx` (`idAsignaturaPlanEstudio` ASC, `idPlanEstudioAsignatura` ASC),
  INDEX `fk_Requisitos2_Asignatura_has_PlanEstudio2_idx` (`iidAsignaturaPlanEstudioRequisito` ASC, `idPlanEstudioRequisito` ASC),
  CONSTRAINT `fk_Requisitos2_Asignatura_has_PlanEstudio1`
    FOREIGN KEY (`idAsignaturaPlanEstudio` , `idPlanEstudioAsignatura`)
    REFERENCES `mydb`.`Asignatura_has_PlanEstudio` (`Asignatura_idAsignatura` , `PlanEstudio_idPlanEstudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Requisitos2_Asignatura_has_PlanEstudio2`
    FOREIGN KEY (`iidAsignaturaPlanEstudioRequisito` , `idPlanEstudioRequisito`)
    REFERENCES `mydb`.`Asignatura_has_PlanEstudio` (`Asignatura_idAsignatura` , `PlanEstudio_idPlanEstudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Requisitos3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Requisitos3` (
  `idRequisitos3` INT NOT NULL,
  `idAsignaturaPlanEstudio` INT NOT NULL,
  `idAsignaturaPlanEstudioRequisito` INT NOT NULL,
  PRIMARY KEY (`idRequisitos3`),
  INDEX `fk_Requisitos3_AsignaturaPlanEstudio1_idx` (`idAsignaturaPlanEstudio` ASC),
  INDEX `fk_Requisitos3_AsignaturaPlanEstudio2_idx` (`idAsignaturaPlanEstudioRequisito` ASC),
  CONSTRAINT `fk_Requisitos3_AsignaturaPlanEstudio1`
    FOREIGN KEY (`idAsignaturaPlanEstudio`)
    REFERENCES `mydb`.`AsignaturaPlanEstudio` (`idAsignaturaPlanEstudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Requisitos3_AsignaturaPlanEstudio2`
    FOREIGN KEY (`idAsignaturaPlanEstudioRequisito`)
    REFERENCES `mydb`.`AsignaturaPlanEstudio` (`idAsignaturaPlanEstudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ObservacionNota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ObservacionNota` (
  `idObservacionNota` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idObservacionNota`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Matricula` (
  `idMatricula` INT NOT NULL,
  `Seccion_idSeccion` INT NOT NULL,
  `Estudiante_numeroCuenta` VARCHAR(45) NOT NULL,
  `fechaRegistro` DATE NULL,
  `calificacion` DOUBLE NULL,
  `ObservacionNota_idObservacionNota` INT NULL,
  `EstadoCalificacion` VARCHAR(1) NULL,
  PRIMARY KEY (`idMatricula`),
  INDEX `fk_Matricula_Seccion1_idx` (`Seccion_idSeccion` ASC),
  INDEX `fk_Matricula_Estudiante1_idx` (`Estudiante_numeroCuenta` ASC),
  INDEX `fk_Matricula_ObservacionNota1_idx` (`ObservacionNota_idObservacionNota` ASC),
  CONSTRAINT `fk_Matricula_Seccion1`
    FOREIGN KEY (`Seccion_idSeccion`)
    REFERENCES `mydb`.`Seccion` (`idSeccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matricula_Estudiante1`
    FOREIGN KEY (`Estudiante_numeroCuenta`)
    REFERENCES `mydb`.`Estudiante` (`numeroCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matricula_ObservacionNota1`
    FOREIGN KEY (`ObservacionNota_idObservacionNota`)
    REFERENCES `mydb`.`ObservacionNota` (`idObservacionNota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estudiante_has_Carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estudiante_has_Carrera` (
  `Estudiante_numeroCuenta` VARCHAR(45) NOT NULL,
  `Carrera_idCarrera` INT NOT NULL,
  `Estado` VARCHAR(1) NULL,
  PRIMARY KEY (`Estudiante_numeroCuenta`, `Carrera_idCarrera`),
  INDEX `fk_Estudiante_has_Carrera_Carrera1_idx` (`Carrera_idCarrera` ASC),
  INDEX `fk_Estudiante_has_Carrera_Estudiante1_idx` (`Estudiante_numeroCuenta` ASC),
  CONSTRAINT `fk_Estudiante_has_Carrera_Estudiante1`
    FOREIGN KEY (`Estudiante_numeroCuenta`)
    REFERENCES `mydb`.`Estudiante` (`numeroCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_has_Carrera_Carrera1`
    FOREIGN KEY (`Carrera_idCarrera`)
    REFERENCES `mydb`.`Carrera` (`idCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Jefe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Jefe` (
  `idJefe` INT NOT NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  `fechaRegistro` DATE NULL,
  PRIMARY KEY (`idJefe`),
  INDEX `fk_Jefe_Empleado1_idx` (`Empleado_idEmpleado` ASC),
  CONSTRAINT `fk_Jefe_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `idEmpleado` INT NOT NULL,
  `pnombre` VARCHAR(45) NULL,
  `snombre` VARCHAR(45) NULL,
  `papellido` VARCHAR(45) NULL,
  `sapellido` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `Jefe_idJefe` INT NULL,
  PRIMARY KEY (`idEmpleado`),
  INDEX `fk_Empleado_Jefe1_idx` (`Jefe_idJefe` ASC),
  CONSTRAINT `fk_Empleado_Jefe1`
    FOREIGN KEY (`Jefe_idJefe`)
    REFERENCES `mydb`.`Jefe` (`idJefe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
