insert into aerolinea.TipoAsiento (idTipoAsiento, descripcion, Asiento_idAsiento) values (1, 'Helminth arthrit NEC', 1);
insert into aerolinea.TipoAsiento (idTipoAsiento, descripcion, Asiento_idAsiento) values (2, 'Sympathetic uveitis', 2);
insert into aerolinea.TipoAsiento (idTipoAsiento, descripcion, Asiento_idAsiento) values (3, 'Fam hx-congen anomalies', 3);
insert into aerolinea.TipoAsiento (idTipoAsiento, descripcion, Asiento_idAsiento) values (4, 'Aftrcre int fixation dev', 4);
insert into aerolinea.TipoAsiento (idTipoAsiento, descripcion, Asiento_idAsiento) values (5, 'Mv-train coll-driver', 5);
insert into aerolinea.TipoAsiento (idTipoAsiento, descripcion, Asiento_idAsiento) values (6, 'Refsum''s disease', 6);
insert into aerolinea.TipoAsiento (idTipoAsiento, descripcion, Asiento_idAsiento) values (7, 'Solitary cyst of breast', 7);
insert into aerolinea.TipoAsiento (idTipoAsiento, descripcion, Asiento_idAsiento) values (8, 'Syphilitic hepatitis', 8);
insert into aerolinea.TipoAsiento (idTipoAsiento, descripcion, Asiento_idAsiento) values (9, 'Brain lac NEC-proln coma', 9);
insert into aerolinea.TipoAsiento (idTipoAsiento, descripcion, Asiento_idAsiento) values (10, 'Acq stenos ear canal NOS', 10);
insert into aerolinea.TipoAsiento (idTipoAsiento, descripcion, Asiento_idAsiento) values (11, 'Peritoneum injury-closed', 11);
insert into aerolinea.TipoAsiento (idTipoAsiento, descripcion, Asiento_idAsiento) values (12, 'Ac apical periodontitis', 12);
insert into aerolinea.TipoAsiento (idTipoAsiento, descripcion, Asiento_idAsiento) values (13, 'TB of adrenal-no exam', 13);
insert into aerolinea.TipoAsiento (idTipoAsiento, descripcion, Asiento_idAsiento) values (14, 'Obstetric shock-deliver', 14);
insert into aerolinea.TipoAsiento (idTipoAsiento, descripcion, Asiento_idAsiento) values (15, 'Abn clinical finding NEC', 15);
insert into aerolinea.TipoAsiento (idTipoAsiento, descripcion, Asiento_idAsiento) values (16, 'Late sympt syphilis NEC', 16);
insert into aerolinea.TipoAsiento (idTipoAsiento, descripcion, Asiento_idAsiento) values (17, 'Jt contracture-unspec', 17);
insert into aerolinea.TipoAsiento (idTipoAsiento, descripcion, Asiento_idAsiento) values (18, 'Disloc midtarsal-open', 18);
insert into aerolinea.TipoAsiento (idTipoAsiento, descripcion, Asiento_idAsiento) values (19, 'Iris/ciliary dis NOS', 19);
insert into aerolinea.TipoAsiento (idTipoAsiento, descripcion, Asiento_idAsiento) values (20, 'Periph station pterygium', 20);
insert into aerolinea.TipoAsiento (idTipoAsiento, descripcion, Asiento_idAsiento) values (21, 'Poisoning-bcg vaccine', 21);
insert into aerolinea.TipoAsiento (idTipoAsiento, descripcion, Asiento_idAsiento) values (22, 'Family hx-gi malignancy', 22);
insert into aerolinea.TipoAsiento (idTipoAsiento, descripcion, Asiento_idAsiento) values (23, 'RR col w oth obj-per NOS', 23);
insert into aerolinea.TipoAsiento (idTipoAsiento, descripcion, Asiento_idAsiento) values (24, 'Basl cell ca skn low lmb', 24);
insert into aerolinea.TipoAsiento (idTipoAsiento, descripcion, Asiento_idAsiento) values (25, 'Fum/vapor up resp inflam', 25);
insert into aerolinea.TipoAsiento (idTipoAsiento, descripcion, Asiento_idAsiento) values (26, 'Adv eff antimycobac NEC', 26);
insert into aerolinea.TipoAsiento (idTipoAsiento, descripcion, Asiento_idAsiento) values (27, 'Acc poison-acids', 27);
insert into aerolinea.TipoAsiento (idTipoAsiento, descripcion, Asiento_idAsiento) values (28, 'Autonomic nerve dis NEC', 28);
insert into aerolinea.TipoAsiento (idTipoAsiento, descripcion, Asiento_idAsiento) values (29, 'Faucial diphtheria', 29);
insert into aerolinea.TipoAsiento (idTipoAsiento, descripcion, Asiento_idAsiento) values (30, 'Lordosis in oth dis', 30);
