insert into aerolinea.Terminal (idTerminal, codigoTerminal, descripcion, Aeropuerto_idAeropuerto) values (1, 'gs-427', 'Phototherapy of Skin, Single', 1);
insert into aerolinea.Terminal (idTerminal, codigoTerminal, descripcion, Aeropuerto_idAeropuerto) values (2, 'ya-431', 'Revise of Intralum Dev in Fallopian Tube, Perc Endo Approach', 2);
insert into aerolinea.Terminal (idTerminal, codigoTerminal, descripcion, Aeropuerto_idAeropuerto) values (3, 'bz-474', 'Detachment at Right Hand, Partial 2nd Ray, Open Approach', 3);
insert into aerolinea.Terminal (idTerminal, codigoTerminal, descripcion, Aeropuerto_idAeropuerto) values (4, 'sy-434', 'Extraction of Accessory Sinus, Open Approach', 4);
insert into aerolinea.Terminal (idTerminal, codigoTerminal, descripcion, Aeropuerto_idAeropuerto) values (5, 'oa-848', 'Restriction of Pulm Trunk with Extralum Dev, Open Approach', 5);
insert into aerolinea.Terminal (idTerminal, codigoTerminal, descripcion, Aeropuerto_idAeropuerto) values (6, 'ca-295', 'Extirpation of Matter from Left Toe Phalanx, Perc Approach', 6);
insert into aerolinea.Terminal (idTerminal, codigoTerminal, descripcion, Aeropuerto_idAeropuerto) values (7, 'ru-165', 'Revision of Autol Sub in R Glenoid Cav, Extern Approach', 7);
insert into aerolinea.Terminal (idTerminal, codigoTerminal, descripcion, Aeropuerto_idAeropuerto) values (8, 'hp-915', 'Restrict L Ext Jugular Vein w Intralum Dev, Open', 8);
insert into aerolinea.Terminal (idTerminal, codigoTerminal, descripcion, Aeropuerto_idAeropuerto) values (9, 'pj-059', 'Replacement of Esophagus with Synth Sub, Via Opening', 9);
insert into aerolinea.Terminal (idTerminal, codigoTerminal, descripcion, Aeropuerto_idAeropuerto) values (10, 'bf-248', 'Supplement Right Vocal Cord with Autol Sub, Endo', 10);
insert into aerolinea.Terminal (idTerminal, codigoTerminal, descripcion, Aeropuerto_idAeropuerto) values (11, 'aa-683', 'Dilate R Fem Art, Bifurc, w Intralum Dev, Perc', 11);
insert into aerolinea.Terminal (idTerminal, codigoTerminal, descripcion, Aeropuerto_idAeropuerto) values (12, 'km-549', 'Revision of Ext Fix in L Wrist Jt, Open Approach', 12);
insert into aerolinea.Terminal (idTerminal, codigoTerminal, descripcion, Aeropuerto_idAeropuerto) values (13, 'hj-016', 'Repair Right Wrist Joint, Percutaneous Endoscopic Approach', 13);
insert into aerolinea.Terminal (idTerminal, codigoTerminal, descripcion, Aeropuerto_idAeropuerto) values (14, 'vp-119', 'Fluoroscopy of L Renal Vein using L Osm Contrast, Guidance', 14);
insert into aerolinea.Terminal (idTerminal, codigoTerminal, descripcion, Aeropuerto_idAeropuerto) values (15, 'uh-995', 'Drainage of Left Internal Carotid Artery, Open Approach', 15);
insert into aerolinea.Terminal (idTerminal, codigoTerminal, descripcion, Aeropuerto_idAeropuerto) values (16, 'ns-481', 'Dilate R Temporal Art, Bifurc, w Intralum Dev, Perc Endo', 16);
insert into aerolinea.Terminal (idTerminal, codigoTerminal, descripcion, Aeropuerto_idAeropuerto) values (17, 'ig-564', 'Reposition Left Ankle Joint with Int Fix, Extern Approach', 17);
insert into aerolinea.Terminal (idTerminal, codigoTerminal, descripcion, Aeropuerto_idAeropuerto) values (18, 'ud-655', 'Change Drainage Device in Skin, External Approach', 18);
insert into aerolinea.Terminal (idTerminal, codigoTerminal, descripcion, Aeropuerto_idAeropuerto) values (19, 'tw-126', 'Dilation of Abd Aorta with 3 Intralum Dev, Open Approach', 19);
insert into aerolinea.Terminal (idTerminal, codigoTerminal, descripcion, Aeropuerto_idAeropuerto) values (20, 'fk-891', 'Drainage of Bilateral Breast, Open Approach', 20);
insert into aerolinea.Terminal (idTerminal, codigoTerminal, descripcion, Aeropuerto_idAeropuerto) values (21, 'wb-454', 'Division of Cervical Plexus, Percutaneous Approach', 21);
insert into aerolinea.Terminal (idTerminal, codigoTerminal, descripcion, Aeropuerto_idAeropuerto) values (22, 'hh-090', 'Replacement of Anal Sphincter with Synth Sub, Open Approach', 22);
insert into aerolinea.Terminal (idTerminal, codigoTerminal, descripcion, Aeropuerto_idAeropuerto) values (23, 'nm-179', 'Drainage of Int Mamm, R Lymph, Perc Endo Approach', 23);
insert into aerolinea.Terminal (idTerminal, codigoTerminal, descripcion, Aeropuerto_idAeropuerto) values (24, 'ok-761', 'Bypass Thor Aorta Asc to L Pulm Art w Autol Art, Perc Endo', 24);
insert into aerolinea.Terminal (idTerminal, codigoTerminal, descripcion, Aeropuerto_idAeropuerto) values (25, 'jf-688', 'Alteration of Upper Jaw, Percutaneous Approach', 25);
insert into aerolinea.Terminal (idTerminal, codigoTerminal, descripcion, Aeropuerto_idAeropuerto) values (26, 'dy-786', 'Excision of Left Internal Carotid Artery, Perc Endo Approach', 26);
insert into aerolinea.Terminal (idTerminal, codigoTerminal, descripcion, Aeropuerto_idAeropuerto) values (27, 'we-578', 'Release Colic Vein, Open Approach', 27);
insert into aerolinea.Terminal (idTerminal, codigoTerminal, descripcion, Aeropuerto_idAeropuerto) values (28, 'nh-189', 'Repair L Low Extrem Bursa/Lig, Perc Approach', 28);
insert into aerolinea.Terminal (idTerminal, codigoTerminal, descripcion, Aeropuerto_idAeropuerto) values (29, 'ob-264', 'Change Cast on Abdominal Wall', 29);
insert into aerolinea.Terminal (idTerminal, codigoTerminal, descripcion, Aeropuerto_idAeropuerto) values (30, 'qk-620', 'Supplement L Int Mamm Art w Nonaut Sub, Perc Endo', 30);
