insert into aerolinea.Reglamentaciones (idReglamentaciones, descripcion, estado, Etapa_idEtapa) values (1, 'Sltr-haris Type I physeal fx lower end of l tibia, sequela', 's', 1);
insert into aerolinea.Reglamentaciones (idReglamentaciones, descripcion, estado, Etapa_idEtapa) values (2, 'Laceration of ovary, bilateral, subsequent encounter', 's', 2);
insert into aerolinea.Reglamentaciones (idReglamentaciones, descripcion, estado, Etapa_idEtapa) values (3, 'Partial physeal arrest, left distal radius', 'o', 3);
insert into aerolinea.Reglamentaciones (idReglamentaciones, descripcion, estado, Etapa_idEtapa) values (4, 'Malignant neoplasm of tonsil', 'c', 4);
insert into aerolinea.Reglamentaciones (idReglamentaciones, descripcion, estado, Etapa_idEtapa) values (5, 'Sprain of MCP joint of left middle finger, init', 'l', 5);
insert into aerolinea.Reglamentaciones (idReglamentaciones, descripcion, estado, Etapa_idEtapa) values (6, 'Exposure to excessive natural cold, sequela', 'o', 6);
insert into aerolinea.Reglamentaciones (idReglamentaciones, descripcion, estado, Etapa_idEtapa) values (7, 'Unspecified fracture of right acetabulum', 'q', 7);
insert into aerolinea.Reglamentaciones (idReglamentaciones, descripcion, estado, Etapa_idEtapa) values (8, 'Nondisp fx of base of nk of l femr, 7thR', 'r', 8);
insert into aerolinea.Reglamentaciones (idReglamentaciones, descripcion, estado, Etapa_idEtapa) values (9, 'Other superficial bite of hip, left hip, sequela', 'r', 9);
insert into aerolinea.Reglamentaciones (idReglamentaciones, descripcion, estado, Etapa_idEtapa) values (10, 'Blister (nonthermal) of right wrist, initial encounter', 'i', 10);
insert into aerolinea.Reglamentaciones (idReglamentaciones, descripcion, estado, Etapa_idEtapa) values (11, 'Unsp injury of musc/fasc/tend triceps, right arm, sequela', 'h', 11);
insert into aerolinea.Reglamentaciones (idReglamentaciones, descripcion, estado, Etapa_idEtapa) values (12, 'Other chondrocalcinosis, right elbow', 'v', 12);
insert into aerolinea.Reglamentaciones (idReglamentaciones, descripcion, estado, Etapa_idEtapa) values (13, 'Toxic effect of contact w sea anemone, self-harm, init', 'f', 13);
insert into aerolinea.Reglamentaciones (idReglamentaciones, descripcion, estado, Etapa_idEtapa) values (14, 'Oth comp specific to multiple gest, first trimester, oth', 'z', 14);
insert into aerolinea.Reglamentaciones (idReglamentaciones, descripcion, estado, Etapa_idEtapa) values (15, 'Other specified injuries left forearm', 'r', 15);
insert into aerolinea.Reglamentaciones (idReglamentaciones, descripcion, estado, Etapa_idEtapa) values (16, 'Ped w convey injured pick-up truck, pk-up/van, unsp, sequela', 'm', 16);
insert into aerolinea.Reglamentaciones (idReglamentaciones, descripcion, estado, Etapa_idEtapa) values (17, 'Disp fx of shaft of fifth metacarpal bone, left hand, init', 'h', 17);
insert into aerolinea.Reglamentaciones (idReglamentaciones, descripcion, estado, Etapa_idEtapa) values (18, 'Lac w/o fb of back wall of thorax w/o penet thoracic cavity', 'r', 18);
insert into aerolinea.Reglamentaciones (idReglamentaciones, descripcion, estado, Etapa_idEtapa) values (19, 'Unsp injury of superfic vn at shldr/up arm, unsp arm, subs', 'w', 19);
insert into aerolinea.Reglamentaciones (idReglamentaciones, descripcion, estado, Etapa_idEtapa) values (20, 'Poisn by antigonadtr/antiestr/antiandrg, NEC, slf-hrm, sqla', 's', 20);
insert into aerolinea.Reglamentaciones (idReglamentaciones, descripcion, estado, Etapa_idEtapa) values (21, 'Pneumococcal arthritis, unspecified shoulder', 'x', 21);
insert into aerolinea.Reglamentaciones (idReglamentaciones, descripcion, estado, Etapa_idEtapa) values (22, 'Superficial foreign body of unspecified wrist, subs encntr', 'o', 22);
insert into aerolinea.Reglamentaciones (idReglamentaciones, descripcion, estado, Etapa_idEtapa) values (23, 'Contusion of left great toe without damage to nail', 'r', 23);
insert into aerolinea.Reglamentaciones (idReglamentaciones, descripcion, estado, Etapa_idEtapa) values (24, 'Unsp fx the lower end r radius, init for opn fx type 3A/B/C', 'd', 24);
insert into aerolinea.Reglamentaciones (idReglamentaciones, descripcion, estado, Etapa_idEtapa) values (25, 'Vomiting without nausea', 'b', 25);
insert into aerolinea.Reglamentaciones (idReglamentaciones, descripcion, estado, Etapa_idEtapa) values (26, 'Maternal care for benign tumor of corpus uteri', 'h', 26);
insert into aerolinea.Reglamentaciones (idReglamentaciones, descripcion, estado, Etapa_idEtapa) values (27, 'Other instability, left elbow', 'z', 27);
insert into aerolinea.Reglamentaciones (idReglamentaciones, descripcion, estado, Etapa_idEtapa) values (28, 'Other specified osteochondropathies of forearm', 'y', 28);
insert into aerolinea.Reglamentaciones (idReglamentaciones, descripcion, estado, Etapa_idEtapa) values (29, 'Nondisp fx of shaft of fifth metacarpal bone, right hand', 'p', 29);
insert into aerolinea.Reglamentaciones (idReglamentaciones, descripcion, estado, Etapa_idEtapa) values (30, 'Displaced fracture of lateral condyle of right tibia', 'y', 30);
