insert into aerolinea.Etapa (idEtapa, descripcion) values (1, 'Other foreign object in larynx causing other injury');
insert into aerolinea.Etapa (idEtapa, descripcion) values (2, 'Oth physl fx lower end of r femur, subs for fx w delay heal');
insert into aerolinea.Etapa (idEtapa, descripcion) values (3, 'Burn of internal genitourinary organs, sequela');
insert into aerolinea.Etapa (idEtapa, descripcion) values (4, 'Oth fx third thor vertebra, subs for fx w delay heal');
insert into aerolinea.Etapa (idEtapa, descripcion) values (5, 'Stable burst fx T9-T10 vertebra, subs for fx w routn heal');
insert into aerolinea.Etapa (idEtapa, descripcion) values (6, 'Underdosing of phenothiazine antipsychot/neurolept, sequela');
insert into aerolinea.Etapa (idEtapa, descripcion) values (7, '3-part fracture of surgical neck of left humerus, sequela');
insert into aerolinea.Etapa (idEtapa, descripcion) values (8, 'Open bite of r frnt wl of thorax w/o penet thor cavity, init');
insert into aerolinea.Etapa (idEtapa, descripcion) values (9, 'Pregnancy with inconclusive fetal viability, fetus 1');
insert into aerolinea.Etapa (idEtapa, descripcion) values (10, 'Partial traumatic amp of two or more right lesser toes, subs');
insert into aerolinea.Etapa (idEtapa, descripcion) values (11, 'Traum rupture of unsp ligament of r idx fngr at MCP/IP jt');
insert into aerolinea.Etapa (idEtapa, descripcion) values (12, 'Underdosing of opium, sequela');
insert into aerolinea.Etapa (idEtapa, descripcion) values (13, 'Burn of first degree of unspecified hand, unspecified site');
insert into aerolinea.Etapa (idEtapa, descripcion) values (14, 'Neuromuscular scoliosis, thoracolumbar region');
insert into aerolinea.Etapa (idEtapa, descripcion) values (15, 'Epileptic spasms, intractable, without status epilepticus');
insert into aerolinea.Etapa (idEtapa, descripcion) values (16, 'Puncture wound with foreign body of nose, initial encounter');
insert into aerolinea.Etapa (idEtapa, descripcion) values (17, 'Congenital lordosis, sacral and sacrococcygeal region');
insert into aerolinea.Etapa (idEtapa, descripcion) values (18, 'Unsp traum nondisp spondylolysis of seventh cervcal vertebra');
insert into aerolinea.Etapa (idEtapa, descripcion) values (19, 'Gastric contents in larynx causing asphyxiation, subs encntr');
insert into aerolinea.Etapa (idEtapa, descripcion) values (20, 'Other Cushing''s syndrome');
insert into aerolinea.Etapa (idEtapa, descripcion) values (21, 'Chondromalacia, right knee');
insert into aerolinea.Etapa (idEtapa, descripcion) values (22, 'Abscess of bursa, unspecified wrist');
insert into aerolinea.Etapa (idEtapa, descripcion) values (23, 'Unspecified injury of fallopian tube, unilateral, sequela');
insert into aerolinea.Etapa (idEtapa, descripcion) values (24, 'Burn of first degree of unspecified foot, subs encntr');
insert into aerolinea.Etapa (idEtapa, descripcion) values (25, 'War op w dest arcrft due to onboard fire, civilian, subs');
insert into aerolinea.Etapa (idEtapa, descripcion) values (26, 'Exposure to prolonged low air pressure');
insert into aerolinea.Etapa (idEtapa, descripcion) values (27, 'Posterior corneal pigmentations, unspecified eye');
insert into aerolinea.Etapa (idEtapa, descripcion) values (28, 'Exposure to bed fire due to oth burning material, subs');
insert into aerolinea.Etapa (idEtapa, descripcion) values (29, 'Insect bite (nonvenomous), left foot, initial encounter');
insert into aerolinea.Etapa (idEtapa, descripcion) values (30, 'Adverse effect of sulfonamides, subsequent encounter');
