insert into aerolinea.TipoLicencia (idTipoLicencia, descripcion) values (1, 'QALoad');
insert into aerolinea.TipoLicencia (idTipoLicencia, descripcion) values (2, 'SLC500');
insert into aerolinea.TipoLicencia (idTipoLicencia, descripcion) values (3, 'QAD');
insert into aerolinea.TipoLicencia (idTipoLicencia, descripcion) values (4, 'Aerodynamics');
insert into aerolinea.TipoLicencia (idTipoLicencia, descripcion) values (5, 'Comic Book Illustration');
insert into aerolinea.TipoLicencia (idTipoLicencia, descripcion) values (6, 'Pressure Vessels');
insert into aerolinea.TipoLicencia (idTipoLicencia, descripcion) values (7, 'Retail Banking');
insert into aerolinea.TipoLicencia (idTipoLicencia, descripcion) values (8, 'Pay TV');
insert into aerolinea.TipoLicencia (idTipoLicencia, descripcion) values (9, 'SBRT');
insert into aerolinea.TipoLicencia (idTipoLicencia, descripcion) values (10, 'Psychiatry');
insert into aerolinea.TipoLicencia (idTipoLicencia, descripcion) values (11, 'Asset Allocation');
insert into aerolinea.TipoLicencia (idTipoLicencia, descripcion) values (12, 'Xajax');
insert into aerolinea.TipoLicencia (idTipoLicencia, descripcion) values (13, 'FMS');
insert into aerolinea.TipoLicencia (idTipoLicencia, descripcion) values (14, 'VCM');
insert into aerolinea.TipoLicencia (idTipoLicencia, descripcion) values (15, 'Biochemistry');
insert into aerolinea.TipoLicencia (idTipoLicencia, descripcion) values (16, 'RSVP');
insert into aerolinea.TipoLicencia (idTipoLicencia, descripcion) values (17, 'Legal Liability');
insert into aerolinea.TipoLicencia (idTipoLicencia, descripcion) values (18, 'MCH');
insert into aerolinea.TipoLicencia (idTipoLicencia, descripcion) values (19, 'PQQs');
insert into aerolinea.TipoLicencia (idTipoLicencia, descripcion) values (20, 'Job Evaluation');
insert into aerolinea.TipoLicencia (idTipoLicencia, descripcion) values (21, 'HPHT');
insert into aerolinea.TipoLicencia (idTipoLicencia, descripcion) values (22, 'EU Funding');
insert into aerolinea.TipoLicencia (idTipoLicencia, descripcion) values (23, 'vShield');
insert into aerolinea.TipoLicencia (idTipoLicencia, descripcion) values (24, 'VMware');
insert into aerolinea.TipoLicencia (idTipoLicencia, descripcion) values (25, 'TBS');
insert into aerolinea.TipoLicencia (idTipoLicencia, descripcion) values (26, 'MySQLi');
insert into aerolinea.TipoLicencia (idTipoLicencia, descripcion) values (27, 'Tally ERP');
insert into aerolinea.TipoLicencia (idTipoLicencia, descripcion) values (28, 'SNF');
insert into aerolinea.TipoLicencia (idTipoLicencia, descripcion) values (29, 'Glass');
insert into aerolinea.TipoLicencia (idTipoLicencia, descripcion) values (30, 'CTC');
