insert into aerolinea.Modelo (idModelo, descripcion, fechaFabricacion, Fabricante_idFabricante) values (1, 'R-Class', '2010-07-12', 1);
insert into aerolinea.Modelo (idModelo, descripcion, fechaFabricacion, Fabricante_idFabricante) values (2, 'Mazda6', '1998-02-28', 2);
insert into aerolinea.Modelo (idModelo, descripcion, fechaFabricacion, Fabricante_idFabricante) values (3, 'Talon', '2000-11-28', 3);
insert into aerolinea.Modelo (idModelo, descripcion, fechaFabricacion, Fabricante_idFabricante) values (4, 'Caravan', '1998-02-22', 4);
insert into aerolinea.Modelo (idModelo, descripcion, fechaFabricacion, Fabricante_idFabricante) values (5, 'Legend', '1998-05-28', 5);
insert into aerolinea.Modelo (idModelo, descripcion, fechaFabricacion, Fabricante_idFabricante) values (6, 'FX', '1998-03-13', 6);
insert into aerolinea.Modelo (idModelo, descripcion, fechaFabricacion, Fabricante_idFabricante) values (7, 'Land Cruiser', '2003-05-15', 7);
insert into aerolinea.Modelo (idModelo, descripcion, fechaFabricacion, Fabricante_idFabricante) values (8, 'SC', '2003-06-05', 8);
insert into aerolinea.Modelo (idModelo, descripcion, fechaFabricacion, Fabricante_idFabricante) values (9, 'Grand Prix', '1998-04-22', 9);
insert into aerolinea.Modelo (idModelo, descripcion, fechaFabricacion, Fabricante_idFabricante) values (10, 'Mazda6', '2010-01-15', 10);
insert into aerolinea.Modelo (idModelo, descripcion, fechaFabricacion, Fabricante_idFabricante) values (11, 'TL', '2003-11-22', 11);
insert into aerolinea.Modelo (idModelo, descripcion, fechaFabricacion, Fabricante_idFabricante) values (12, 'Ram 2500', '2010-04-26', 12);
insert into aerolinea.Modelo (idModelo, descripcion, fechaFabricacion, Fabricante_idFabricante) values (13, 'Ram Van 2500', '1998-08-14', 13);
insert into aerolinea.Modelo (idModelo, descripcion, fechaFabricacion, Fabricante_idFabricante) values (14, 'Crown Victoria', '2003-04-18', 14);
insert into aerolinea.Modelo (idModelo, descripcion, fechaFabricacion, Fabricante_idFabricante) values (15, 'Yukon XL 1500', '2010-11-27', 15);
insert into aerolinea.Modelo (idModelo, descripcion, fechaFabricacion, Fabricante_idFabricante) values (16, 'Avenger', '1998-11-20', 16);
insert into aerolinea.Modelo (idModelo, descripcion, fechaFabricacion, Fabricante_idFabricante) values (17, 'Trans Sport', '2019-03-18', 17);
insert into aerolinea.Modelo (idModelo, descripcion, fechaFabricacion, Fabricante_idFabricante) values (18, 'Defender 90', '2010-07-11', 18);
insert into aerolinea.Modelo (idModelo, descripcion, fechaFabricacion, Fabricante_idFabricante) values (19, 'Express 2500', '2010-02-22', 19);
insert into aerolinea.Modelo (idModelo, descripcion, fechaFabricacion, Fabricante_idFabricante) values (20, 'Fifth Ave', '2019-03-08', 20);
insert into aerolinea.Modelo (idModelo, descripcion, fechaFabricacion, Fabricante_idFabricante) values (21, 'Vision', '2003-05-02', 21);
insert into aerolinea.Modelo (idModelo, descripcion, fechaFabricacion, Fabricante_idFabricante) values (22, 'Ram 3500', '1998-06-28', 22);
insert into aerolinea.Modelo (idModelo, descripcion, fechaFabricacion, Fabricante_idFabricante) values (23, 'LeSabre', '2003-01-11', 23);
insert into aerolinea.Modelo (idModelo, descripcion, fechaFabricacion, Fabricante_idFabricante) values (24, 'LS', '1998-12-12', 24);
insert into aerolinea.Modelo (idModelo, descripcion, fechaFabricacion, Fabricante_idFabricante) values (25, 'Celica', '2010-05-01', 25);
insert into aerolinea.Modelo (idModelo, descripcion, fechaFabricacion, Fabricante_idFabricante) values (26, 'Rodeo Sport', '2003-02-14', 26);
insert into aerolinea.Modelo (idModelo, descripcion, fechaFabricacion, Fabricante_idFabricante) values (27, 'Phantom', '2010-11-13', 27);
insert into aerolinea.Modelo (idModelo, descripcion, fechaFabricacion, Fabricante_idFabricante) values (28, 'Laser', '2010-03-10', 28);
insert into aerolinea.Modelo (idModelo, descripcion, fechaFabricacion, Fabricante_idFabricante) values (29, 'Rodeo', '2000-09-22', 29);
insert into aerolinea.Modelo (idModelo, descripcion, fechaFabricacion, Fabricante_idFabricante) values (30, 'Highlander', '1998-07-26', 30);
