insert into aerolinea.EtapaBoleto (idEtapaBoleto, descripcion, estado) values (1, 'Removal of Drainage Device from Fallopian Tube, Endo', 'l');
insert into aerolinea.EtapaBoleto (idEtapaBoleto, descripcion, estado) values (2, 'Fluoroscopy of Bilateral Fallopian Tubes using Oth Contrast', 'w');
insert into aerolinea.EtapaBoleto (idEtapaBoleto, descripcion, estado) values (3, 'Restriction of Right Renal Vein, Percutaneous Approach', 'a');
insert into aerolinea.EtapaBoleto (idEtapaBoleto, descripcion, estado) values (4, 'Bypass Sup Vena Cava to R Pulm Vn w Autol Vn, Open', 'm');
insert into aerolinea.EtapaBoleto (idEtapaBoleto, descripcion, estado) values (5, 'Revision of Nonaut Sub in R Tarsal, Perc Endo Approach', 'p');
insert into aerolinea.EtapaBoleto (idEtapaBoleto, descripcion, estado) values (6, 'Transfer Oculomotor Nrv to Hypogloss Nrv, Perc Endo Approach', 'g');
insert into aerolinea.EtapaBoleto (idEtapaBoleto, descripcion, estado) values (7, 'Removal of Radioactive Element from Abd Wall, Perc Approach', 'd');
insert into aerolinea.EtapaBoleto (idEtapaBoleto, descripcion, estado) values (8, 'Excision of Pons, Percutaneous Endoscopic Approach, Diagn', 'w');
insert into aerolinea.EtapaBoleto (idEtapaBoleto, descripcion, estado) values (9, 'Drainage of Pancreatic Duct, Via Opening', 'y');
insert into aerolinea.EtapaBoleto (idEtapaBoleto, descripcion, estado) values (10, 'Drain of L Temporal Bone with Drain Dev, Perc Endo Approach', 'u');
insert into aerolinea.EtapaBoleto (idEtapaBoleto, descripcion, estado) values (11, 'Repair Right Tympanic Membrane, Endo', 'e');
insert into aerolinea.EtapaBoleto (idEtapaBoleto, descripcion, estado) values (12, 'Release Left Foot Muscle, Percutaneous Approach', 't');
insert into aerolinea.EtapaBoleto (idEtapaBoleto, descripcion, estado) values (13, 'Drainage of Right Pleura with Drain Dev, Perc Endo Approach', 'y');
insert into aerolinea.EtapaBoleto (idEtapaBoleto, descripcion, estado) values (14, 'Insertion of Infusion Device into Kidney, Via Opening', 'e');
insert into aerolinea.EtapaBoleto (idEtapaBoleto, descripcion, estado) values (15, 'LDR Brachytherapy of Adrenal Glands using Iodine 125', 'v');
insert into aerolinea.EtapaBoleto (idEtapaBoleto, descripcion, estado) values (16, 'Supplement Ventricular Sept w Nonaut Sub, Perc Endo', 'y');
insert into aerolinea.EtapaBoleto (idEtapaBoleto, descripcion, estado) values (17, 'Bypass Inf Mesent Vein to Low Vein w Synth Sub, Open', 'z');
insert into aerolinea.EtapaBoleto (idEtapaBoleto, descripcion, estado) values (18, 'Reposition Left Glenoid Cavity, Perc Endo Approach', 'y');
insert into aerolinea.EtapaBoleto (idEtapaBoleto, descripcion, estado) values (19, 'Supplement Right Nipple with Nonaut Sub, Extern Approach', 'k');
insert into aerolinea.EtapaBoleto (idEtapaBoleto, descripcion, estado) values (20, 'Reposition R Humeral Head w Monopln Ext Fix, Perc Endo', 'h');
insert into aerolinea.EtapaBoleto (idEtapaBoleto, descripcion, estado) values (21, 'Removal of Stimulator Lead from Ureter, Open Approach', 'r');
insert into aerolinea.EtapaBoleto (idEtapaBoleto, descripcion, estado) values (22, 'Plain Radiography of L Ext Carotid using Oth Contrast', 'b');
insert into aerolinea.EtapaBoleto (idEtapaBoleto, descripcion, estado) values (23, 'Reposition Right Lower Leg Muscle, Open Approach', 'g');
insert into aerolinea.EtapaBoleto (idEtapaBoleto, descripcion, estado) values (24, 'Extracorporeal Therapies, Phys Sys, Shock Wave Therapy', 'k');
insert into aerolinea.EtapaBoleto (idEtapaBoleto, descripcion, estado) values (25, 'Reattachment of Right Hepatic Duct, Open Approach', 'c');
insert into aerolinea.EtapaBoleto (idEtapaBoleto, descripcion, estado) values (26, 'Dilation of Mid Colic Art with 3 Intralum Dev, Perc Approach', 'f');
insert into aerolinea.EtapaBoleto (idEtapaBoleto, descripcion, estado) values (27, 'Occlusion of Duodenum with Extralum Dev, Perc Endo Approach', 'x');
insert into aerolinea.EtapaBoleto (idEtapaBoleto, descripcion, estado) values (28, 'Beam Radiation of Cervix using Photons >10 MeV', 'k');
insert into aerolinea.EtapaBoleto (idEtapaBoleto, descripcion, estado) values (29, 'Drainage of Right Upper Leg Muscle, Open Approach', 't');
insert into aerolinea.EtapaBoleto (idEtapaBoleto, descripcion, estado) values (30, 'Revision of Synthetic Substitute in Cerv Jt, Extern Approach', 'd');
