insert into aerolinea.pais (idPais, nombre, nombreCorto) values (1, 'China', 'CN');
insert into aerolinea.pais (idPais, nombre, nombreCorto) values (2, 'Indonesia', 'ID');
insert into aerolinea.pais (idPais, nombre, nombreCorto) values (3, 'Portugal', 'PT');
insert into aerolinea.pais (idPais, nombre, nombreCorto) values (4, 'China', 'CN');
insert into aerolinea.pais (idPais, nombre, nombreCorto) values (5, 'Russia', 'RU');
insert into aerolinea.pais (idPais, nombre, nombreCorto) values (6, 'Philippines', 'PH');
insert into aerolinea.pais (idPais, nombre, nombreCorto) values (7, 'China', 'CN');
insert into aerolinea.pais (idPais, nombre, nombreCorto) values (8, 'Greece', 'GR');
insert into aerolinea.pais (idPais, nombre, nombreCorto) values (9, 'China', 'CN');
insert into aerolinea.pais (idPais, nombre, nombreCorto) values (10, 'Australia', 'AU');
insert into aerolinea.pais (idPais, nombre, nombreCorto) values (11, 'South Africa', 'ZA');
insert into aerolinea.pais (idPais, nombre, nombreCorto) values (12, 'Brazil', 'BR');
insert into aerolinea.pais (idPais, nombre, nombreCorto) values (13, 'Mexico', 'MX');
insert into aerolinea.pais (idPais, nombre, nombreCorto) values (14, 'Portugal', 'PT');
insert into aerolinea.pais (idPais, nombre, nombreCorto) values (15, 'China', 'CN');
insert into aerolinea.pais (idPais, nombre, nombreCorto) values (16, 'Iceland', 'IS');
insert into aerolinea.pais (idPais, nombre, nombreCorto) values (17, 'Indonesia', 'ID');
insert into aerolinea.pais (idPais, nombre, nombreCorto) values (18, 'Brazil', 'BR');
insert into aerolinea.pais (idPais, nombre, nombreCorto) values (19, 'China', 'CN');
insert into aerolinea.pais (idPais, nombre, nombreCorto) values (20, 'Tajikistan', 'TJ');
insert into aerolinea.pais (idPais, nombre, nombreCorto) values (21, 'China', 'CN');
insert into aerolinea.pais (idPais, nombre, nombreCorto) values (22, 'Democratic Republic of the Congo', 'CD');
insert into aerolinea.pais (idPais, nombre, nombreCorto) values (23, 'Indonesia', 'ID');
insert into aerolinea.pais (idPais, nombre, nombreCorto) values (24, 'China', 'CN');
insert into aerolinea.pais (idPais, nombre, nombreCorto) values (25, 'China', 'CN');
insert into aerolinea.pais (idPais, nombre, nombreCorto) values (26, 'France', 'FR');
insert into aerolinea.pais (idPais, nombre, nombreCorto) values (27, 'Brazil', 'BR');
insert into aerolinea.pais (idPais, nombre, nombreCorto) values (28, 'Ivory Coast', 'CI');
insert into aerolinea.pais (idPais, nombre, nombreCorto) values (29, 'Portugal', 'PT');
insert into aerolinea.pais (idPais, nombre, nombreCorto) values (30, 'Indonesia', 'ID');
