insert into aerolinea.RequisitoBoleto (idRequisitoBoleto, descripcion, estado, EtapaBoleto_idEtapaBoleto) values (1, 'Replacement of R Verteb Art with Synth Sub, Open Approach', 'p', 1);
insert into aerolinea.RequisitoBoleto (idRequisitoBoleto, descripcion, estado, EtapaBoleto_idEtapaBoleto) values (2, 'Robotic Assisted Procedure of Up Extrem, Perc Endo Approach', 'x', 2);
insert into aerolinea.RequisitoBoleto (idRequisitoBoleto, descripcion, estado, EtapaBoleto_idEtapaBoleto) values (3, 'Restrict of R Com Iliac Art with Intralum Dev, Perc Approach', 'v', 3);
insert into aerolinea.RequisitoBoleto (idRequisitoBoleto, descripcion, estado, EtapaBoleto_idEtapaBoleto) values (4, 'Reposition Left Thumb Phalanx with Int Fix, Open Approach', 'f', 4);
insert into aerolinea.RequisitoBoleto (idRequisitoBoleto, descripcion, estado, EtapaBoleto_idEtapaBoleto) values (5, 'Insertion of Neuro Lead into Spinal Cord, Open Approach', 'n', 5);
insert into aerolinea.RequisitoBoleto (idRequisitoBoleto, descripcion, estado, EtapaBoleto_idEtapaBoleto) values (6, 'CT Scan of L Renal Vein using L Osm Contrast', 'l', 6);
insert into aerolinea.RequisitoBoleto (idRequisitoBoleto, descripcion, estado, EtapaBoleto_idEtapaBoleto) values (7, 'Alteration of L Low Arm with Synth Sub, Perc Endo Approach', 'n', 7);
insert into aerolinea.RequisitoBoleto (idRequisitoBoleto, descripcion, estado, EtapaBoleto_idEtapaBoleto) values (8, 'Extirpation of Matter from Sacral Plexus, Perc Approach', 'd', 8);
insert into aerolinea.RequisitoBoleto (idRequisitoBoleto, descripcion, estado, EtapaBoleto_idEtapaBoleto) values (9, 'Reposition Left Vertebral Vein, Percutaneous Approach', 'z', 9);
insert into aerolinea.RequisitoBoleto (idRequisitoBoleto, descripcion, estado, EtapaBoleto_idEtapaBoleto) values (10, 'Insertion of Spacer into Lum Jt, Perc Endo Approach', 'r', 10);
insert into aerolinea.RequisitoBoleto (idRequisitoBoleto, descripcion, estado, EtapaBoleto_idEtapaBoleto) values (11, 'Drainage of Trigeminal Nerve with Drain Dev, Open Approach', 'k', 11);
insert into aerolinea.RequisitoBoleto (idRequisitoBoleto, descripcion, estado, EtapaBoleto_idEtapaBoleto) values (12, 'Introduce Monoclonal Antibody in Pleural Cav, Perc', 'm', 12);
insert into aerolinea.RequisitoBoleto (idRequisitoBoleto, descripcion, estado, EtapaBoleto_idEtapaBoleto) values (13, 'Remove Infusion Dev from L Metacarpophal Jt, Open', 'k', 13);
insert into aerolinea.RequisitoBoleto (idRequisitoBoleto, descripcion, estado, EtapaBoleto_idEtapaBoleto) values (14, 'Resection of Soft Palate, Open Approach', 'o', 14);
insert into aerolinea.RequisitoBoleto (idRequisitoBoleto, descripcion, estado, EtapaBoleto_idEtapaBoleto) values (15, 'Change Intermittent Pressure Device on Right Lower Leg', 'o', 15);
insert into aerolinea.RequisitoBoleto (idRequisitoBoleto, descripcion, estado, EtapaBoleto_idEtapaBoleto) values (16, 'Removal of Spacer from R Tarsal Jt, Perc Endo Approach', 's', 16);
insert into aerolinea.RequisitoBoleto (idRequisitoBoleto, descripcion, estado, EtapaBoleto_idEtapaBoleto) values (17, 'Revision of Radioact Elem in Pericard Cav, Extern Approach', 'v', 17);
insert into aerolinea.RequisitoBoleto (idRequisitoBoleto, descripcion, estado, EtapaBoleto_idEtapaBoleto) values (18, 'Removal of Autol Sub from R Acromioclav Jt, Perc Approach', 'k', 18);
insert into aerolinea.RequisitoBoleto (idRequisitoBoleto, descripcion, estado, EtapaBoleto_idEtapaBoleto) values (19, 'Bypass Ileum to Anus, Percutaneous Endoscopic Approach', 'x', 19);
insert into aerolinea.RequisitoBoleto (idRequisitoBoleto, descripcion, estado, EtapaBoleto_idEtapaBoleto) values (20, 'Chiropractic Manipulation of Lumbar Region, Short Lever', 'v', 20);
insert into aerolinea.RequisitoBoleto (idRequisitoBoleto, descripcion, estado, EtapaBoleto_idEtapaBoleto) values (21, 'Revision of Spacer in R Acromioclav Jt, Perc Endo Approach', 'v', 21);
insert into aerolinea.RequisitoBoleto (idRequisitoBoleto, descripcion, estado, EtapaBoleto_idEtapaBoleto) values (22, 'Destruction of Right Tarsal, Perc Endo Approach', 'w', 22);
insert into aerolinea.RequisitoBoleto (idRequisitoBoleto, descripcion, estado, EtapaBoleto_idEtapaBoleto) values (23, 'Restriction of Left Hepatic Duct, Perc Endo Approach', 't', 23);
insert into aerolinea.RequisitoBoleto (idRequisitoBoleto, descripcion, estado, EtapaBoleto_idEtapaBoleto) values (24, 'Transfer Left Thorax Bursa and Ligament, Open Approach', 't', 24);
insert into aerolinea.RequisitoBoleto (idRequisitoBoleto, descripcion, estado, EtapaBoleto_idEtapaBoleto) values (25, 'Dilate of R Mid Lobe Bronc with Intralum Dev, Perc Approach', 'a', 25);
insert into aerolinea.RequisitoBoleto (idRequisitoBoleto, descripcion, estado, EtapaBoleto_idEtapaBoleto) values (26, 'Replacement of R Ethmoid Bone with Nonaut Sub, Open Approach', 'p', 26);
insert into aerolinea.RequisitoBoleto (idRequisitoBoleto, descripcion, estado, EtapaBoleto_idEtapaBoleto) values (27, 'Destruction of Left Greater Saphenous Vein, Open Approach', 'k', 27);
insert into aerolinea.RequisitoBoleto (idRequisitoBoleto, descripcion, estado, EtapaBoleto_idEtapaBoleto) values (28, 'Insertion of Infusion Device into L Buttock, Perc Approach', 'f', 28);
insert into aerolinea.RequisitoBoleto (idRequisitoBoleto, descripcion, estado, EtapaBoleto_idEtapaBoleto) values (29, 'Resection of Sacrococcygeal Joint, Open Approach', 'a', 29);
insert into aerolinea.RequisitoBoleto (idRequisitoBoleto, descripcion, estado, EtapaBoleto_idEtapaBoleto) values (30, 'Beam Radiation of Pituitary Gland using Photons <1 MeV', 'a', 30);
