insert into aerolinea.TipoMantenimiento (idTipoMantenimiento, descripcion) values (1, 'Unstable lie-delivered');
insert into aerolinea.TipoMantenimiento (idTipoMantenimiento, descripcion) values (2, 'Dust pneumonopathy NEC');
insert into aerolinea.TipoMantenimiento (idTipoMantenimiento, descripcion) values (3, 'Prem rupt memb-antepart');
insert into aerolinea.TipoMantenimiento (idTipoMantenimiento, descripcion) values (4, 'Depend-supplement oxygen');
insert into aerolinea.TipoMantenimiento (idTipoMantenimiento, descripcion) values (5, 'Ant disloc prox tibia-cl');
insert into aerolinea.TipoMantenimiento (idTipoMantenimiento, descripcion) values (6, 'Dislocat sternum-closed');
insert into aerolinea.TipoMantenimiento (idTipoMantenimiento, descripcion) values (7, 'Candidal vulvovaginitis');
insert into aerolinea.TipoMantenimiento (idTipoMantenimiento, descripcion) values (8, 'Cong cornea opac aff vis');
insert into aerolinea.TipoMantenimiento (idTipoMantenimiento, descripcion) values (9, 'Miliary TB NOS-oth test');
insert into aerolinea.TipoMantenimiento (idTipoMantenimiento, descripcion) values (10, 'Open wnd mouth NOS-compl');
insert into aerolinea.TipoMantenimiento (idTipoMantenimiento, descripcion) values (11, 'Hdgk prg unsp xtrndl org');
insert into aerolinea.TipoMantenimiento (idTipoMantenimiento, descripcion) values (12, 'Androgen insensitvty syn');
insert into aerolinea.TipoMantenimiento (idTipoMantenimiento, descripcion) values (13, 'Myelitis follwg immune');
insert into aerolinea.TipoMantenimiento (idTipoMantenimiento, descripcion) values (14, 'Cord compl NEC-antepart');
insert into aerolinea.TipoMantenimiento (idTipoMantenimiento, descripcion) values (15, '60-69% bdy brn/20-29% 3d');
insert into aerolinea.TipoMantenimiento (idTipoMantenimiento, descripcion) values (16, 'Forearm deformity NOS');
insert into aerolinea.TipoMantenimiento (idTipoMantenimiento, descripcion) values (17, 'Other apnea of newborn');
insert into aerolinea.TipoMantenimiento (idTipoMantenimiento, descripcion) values (18, 'Unstable lie-unspecified');
insert into aerolinea.TipoMantenimiento (idTipoMantenimiento, descripcion) values (19, 'Injury-moving object');
insert into aerolinea.TipoMantenimiento (idTipoMantenimiento, descripcion) values (20, 'Lymphoid mal NEC thorax');
insert into aerolinea.TipoMantenimiento (idTipoMantenimiento, descripcion) values (21, 'Cervical (HPV) DNA pos');
insert into aerolinea.TipoMantenimiento (idTipoMantenimiento, descripcion) values (22, 'Int inf e coli entrhmrg');
insert into aerolinea.TipoMantenimiento (idTipoMantenimiento, descripcion) values (23, 'Part edentulsm,class III');
insert into aerolinea.TipoMantenimiento (idTipoMantenimiento, descripcion) values (24, 'Sprain metacarpophalang');
insert into aerolinea.TipoMantenimiento (idTipoMantenimiento, descripcion) values (25, 'Old magnet fb, post wall');
insert into aerolinea.TipoMantenimiento (idTipoMantenimiento, descripcion) values (26, 'Status amput thumb');
insert into aerolinea.TipoMantenimiento (idTipoMantenimiento, descripcion) values (27, 'Hodgkins sarcoma pelvic');
insert into aerolinea.TipoMantenimiento (idTipoMantenimiento, descripcion) values (28, 'Lacriml punctum stenosis');
insert into aerolinea.TipoMantenimiento (idTipoMantenimiento, descripcion) values (29, 'Inj nerve pelv/leg NOS');
insert into aerolinea.TipoMantenimiento (idTipoMantenimiento, descripcion) values (30, 'Family hx-arthritis');
