insert into aerolinea.Area (idArea, descripcion) values (1, 'Dilate of R Peroneal Art with 3 Intralum Dev, Open Approach');
insert into aerolinea.Area (idArea, descripcion) values (2, 'Supplement Aortic Valve with Nonaut Sub, Perc Endo Approach');
insert into aerolinea.Area (idArea, descripcion) values (3, 'Sensory Aids Assessment using Tympanometer');
insert into aerolinea.Area (idArea, descripcion) values (4, 'Insertion of Ext Fix into R Metatarsophal Jt, Open Approach');
insert into aerolinea.Area (idArea, descripcion) values (5, 'Detachment at Right Foot, Partial 3rd Ray, Open Approach');
insert into aerolinea.Area (idArea, descripcion) values (6, 'Revision of Synth Sub in L Tarsal Jt, Perc Endo Approach');
insert into aerolinea.Area (idArea, descripcion) values (7, 'Drainage of Lesser Omentum with Drain Dev, Perc Approach');
insert into aerolinea.Area (idArea, descripcion) values (8, 'Extirpation of Matter from Pericardial Cavity, Open Approach');
insert into aerolinea.Area (idArea, descripcion) values (9, 'Supplement L Temporomandib Jt with Nonaut Sub, Open Approach');
insert into aerolinea.Area (idArea, descripcion) values (10, 'Removal of Ext Fix from L Toe Phalanx, Extern Approach');
insert into aerolinea.Area (idArea, descripcion) values (11, 'Destruction of Cervical Nerve, Percutaneous Approach');
insert into aerolinea.Area (idArea, descripcion) values (12, 'Replace of R Ext Iliac Vein with Synth Sub, Open Approach');
insert into aerolinea.Area (idArea, descripcion) values (13, 'Fluoroscopy of Bi Renal Vein using H Osm Contrast, Guidance');
insert into aerolinea.Area (idArea, descripcion) values (14, 'Dilation of Intracranial Artery, Open Approach');
insert into aerolinea.Area (idArea, descripcion) values (15, 'Removal of Drainage Device from Liver, Open Approach');
insert into aerolinea.Area (idArea, descripcion) values (16, 'Indiv Psychotherapy for Substance Abuse Treatment, Cognitive');
insert into aerolinea.Area (idArea, descripcion) values (17, 'Removal of Nonaut Sub from R Metacarpocarp Jt, Perc Approach');
insert into aerolinea.Area (idArea, descripcion) values (18, 'Extirpate matter from R Int Carotid, Bifurc, Open');
insert into aerolinea.Area (idArea, descripcion) values (19, 'Control Bleeding in Left Shoulder Region, Perc Endo Approach');
insert into aerolinea.Area (idArea, descripcion) values (20, 'Occlusion L Up Lobe Bronc w Extralum Dev, Perc Endo');
insert into aerolinea.Area (idArea, descripcion) values (21, 'Computerized Tomography (CT Scan) of Chest, Abd & Pelvis');
insert into aerolinea.Area (idArea, descripcion) values (22, 'Extraction of R Up Arm Subcu/Fascia, Perc Approach');
insert into aerolinea.Area (idArea, descripcion) values (23, 'Insert of Infusion Dev into Uterus & Cervix, Open Approach');
insert into aerolinea.Area (idArea, descripcion) values (24, 'Bypass Thor Aorta Asc to Pulm Trunk w Zooplastic, Perc Endo');
insert into aerolinea.Area (idArea, descripcion) values (25, 'Plain Radiography of Prostate using High Osmolar Contrast');
insert into aerolinea.Area (idArea, descripcion) values (26, 'Removal of Nonaut Sub from R Acetabulum, Open Approach');
insert into aerolinea.Area (idArea, descripcion) values (27, 'Extirpate of Matter from L Peroneal Art, Perc Endo Approach');
insert into aerolinea.Area (idArea, descripcion) values (28, 'Drainage of R Up Extrem with Drain Dev, Open Approach');
insert into aerolinea.Area (idArea, descripcion) values (29, 'Change Bandage on Right Lower Arm');
insert into aerolinea.Area (idArea, descripcion) values (30, 'Revision of Autol Sub in Lumsac Disc, Perc Approach');
