insert into aerolinea.Cargo (idCargo, descripcion, Area_idArea) values (1, 'Extirpate matter from R Low Extrem Bursa/Lig, Perc', 1);
insert into aerolinea.Cargo (idCargo, descripcion, Area_idArea) values (2, 'Supplement Left Atrium with Synth Sub, Perc Endo Approach', 2);
insert into aerolinea.Cargo (idCargo, descripcion, Area_idArea) values (3, 'Replacement of Right Nipple with Nonaut Sub, Extern Approach', 3);
insert into aerolinea.Cargo (idCargo, descripcion, Area_idArea) values (4, 'Revision of Drainage Device in Low Intest Tract, Via Opening', 4);
insert into aerolinea.Cargo (idCargo, descripcion, Area_idArea) values (5, 'Bypass Sup Vena Cava to L Pulm Art w Nonaut Sub, Open', 5);
insert into aerolinea.Cargo (idCargo, descripcion, Area_idArea) values (6, 'Replacement of Buccal Mucosa with Synth Sub, Perc Approach', 6);
insert into aerolinea.Cargo (idCargo, descripcion, Area_idArea) values (7, 'Removal of Synthetic Substitute from L Ulna, Perc Approach', 7);
insert into aerolinea.Cargo (idCargo, descripcion, Area_idArea) values (8, 'Replacement of Lesser Omentum with Synth Sub, Open Approach', 8);
insert into aerolinea.Cargo (idCargo, descripcion, Area_idArea) values (9, 'Insert of Facet Stabl Dev into T-lum Jt, Perc Endo Approach', 9);
insert into aerolinea.Cargo (idCargo, descripcion, Area_idArea) values (10, 'Insertion of Infusion Device into R Ulnar Art, Open Approach', 10);
insert into aerolinea.Cargo (idCargo, descripcion, Area_idArea) values (11, 'Reposition Right Pulmonary Vein, Open Approach', 11);
insert into aerolinea.Cargo (idCargo, descripcion, Area_idArea) values (12, 'Supplement R Low Leg with Synth Sub, Perc Endo Approach', 12);
insert into aerolinea.Cargo (idCargo, descripcion, Area_idArea) values (13, 'Supplement Urethra with Nonaut Sub, Open Approach', 13);
insert into aerolinea.Cargo (idCargo, descripcion, Area_idArea) values (14, 'Excision of Right Metatarsal, Percutaneous Approach, Diagn', 14);
insert into aerolinea.Cargo (idCargo, descripcion, Area_idArea) values (15, 'Drainage of Right Metacarpocarpal Joint, Perc Approach', 15);
insert into aerolinea.Cargo (idCargo, descripcion, Area_idArea) values (16, 'Bypass Ascending Colon to Asc Colon with Synth Sub, Endo', 16);
insert into aerolinea.Cargo (idCargo, descripcion, Area_idArea) values (17, 'Insertion of Infusion Device into Testis, Via Opening', 17);
insert into aerolinea.Cargo (idCargo, descripcion, Area_idArea) values (18, 'HDR Brachytherapy of Prostate using Californium 252', 18);
insert into aerolinea.Cargo (idCargo, descripcion, Area_idArea) values (19, 'Insertion of Spacer into L Elbow Jt, Perc Endo Approach', 19);
insert into aerolinea.Cargo (idCargo, descripcion, Area_idArea) values (20, 'Replacement of Left Nipple with Synth Sub, Extern Approach', 20);
insert into aerolinea.Cargo (idCargo, descripcion, Area_idArea) values (21, 'Ultrasonography of Bi Int Carotid, Intravasc', 21);
insert into aerolinea.Cargo (idCargo, descripcion, Area_idArea) values (22, 'Dilation of 3 Cor Art with Radioact Intralum, Perc Approach', 22);
insert into aerolinea.Cargo (idCargo, descripcion, Area_idArea) values (23, 'Revision of Synth Sub in R Thumb Phalanx, Perc Endo Approach', 23);
insert into aerolinea.Cargo (idCargo, descripcion, Area_idArea) values (24, 'Restrict of R Lacrml Duct with Intralum Dev, Perc Approach', 24);
insert into aerolinea.Cargo (idCargo, descripcion, Area_idArea) values (25, 'Removal of Ext Fix from R Toe Phalanx, Perc Endo Approach', 25);
insert into aerolinea.Cargo (idCargo, descripcion, Area_idArea) values (26, 'Excision of Left Upper Leg Tendon, Perc Endo Approach, Diagn', 26);
insert into aerolinea.Cargo (idCargo, descripcion, Area_idArea) values (27, 'Extirpation of Matter from Left Acetabulum, Perc Approach', 27);
insert into aerolinea.Cargo (idCargo, descripcion, Area_idArea) values (28, 'Bypass Bladder to Ileocutan with Synth Sub, Open Approach', 28);
insert into aerolinea.Cargo (idCargo, descripcion, Area_idArea) values (29, 'Reposition L Humeral Shaft w Monopln Ext Fix, Perc', 29);
insert into aerolinea.Cargo (idCargo, descripcion, Area_idArea) values (30, 'Osteopathic Treatment of Low Extrem using Fascial Release', 30);
