insert into aerolinea.TipoClase (idTipoClase, descripcion, numeroMaletaPermitida) values (1, 'Open red-int fix finger', 1);
insert into aerolinea.TipoClase (idTipoClase, descripcion, numeroMaletaPermitida) values (2, 'Cl reduc disloc-hip', 8);
insert into aerolinea.TipoClase (idTipoClase, descripcion, numeroMaletaPermitida) values (3, 'Opn bil ind ing hern NEC', 10);
insert into aerolinea.TipoClase (idTipoClase, descripcion, numeroMaletaPermitida) values (4, 'Remove both fallop tubes', 10);
insert into aerolinea.TipoClase (idTipoClase, descripcion, numeroMaletaPermitida) values (5, 'Autopsy', 9);
insert into aerolinea.TipoClase (idTipoClase, descripcion, numeroMaletaPermitida) values (6, 'Scler fistulizing op NEC', 3);
insert into aerolinea.TipoClase (idTipoClase, descripcion, numeroMaletaPermitida) values (7, 'Remov cholecystost tube', 6);
insert into aerolinea.TipoClase (idTipoClase, descripcion, numeroMaletaPermitida) values (8, 'Hip surface, cermc/cermc', 4);
insert into aerolinea.TipoClase (idTipoClase, descripcion, numeroMaletaPermitida) values (9, 'Therapeut distent bladd', 3);
insert into aerolinea.TipoClase (idTipoClase, descripcion, numeroMaletaPermitida) values (10, 'Sympathetic nerve biopsy', 10);
insert into aerolinea.TipoClase (idTipoClase, descripcion, numeroMaletaPermitida) values (11, 'Man replace invert uter', 9);
insert into aerolinea.TipoClase (idTipoClase, descripcion, numeroMaletaPermitida) values (12, 'Myotomy of colon NEC', 4);
insert into aerolinea.TipoClase (idTipoClase, descripcion, numeroMaletaPermitida) values (13, 'Closed biopsy trachea', 9);
insert into aerolinea.TipoClase (idTipoClase, descripcion, numeroMaletaPermitida) values (14, 'Open mediastinal biopsy', 5);
insert into aerolinea.TipoClase (idTipoClase, descripcion, numeroMaletaPermitida) values (15, 'Ins or rep cement spacer', 6);
insert into aerolinea.TipoClase (idTipoClase, descripcion, numeroMaletaPermitida) values (16, 'Radical groin dissection', 10);
insert into aerolinea.TipoClase (idTipoClase, descripcion, numeroMaletaPermitida) values (17, 'Opn/oth rep hrt vlv NOS', 1);
insert into aerolinea.TipoClase (idTipoClase, descripcion, numeroMaletaPermitida) values (18, 'Thyroid reimplantation', 10);
insert into aerolinea.TipoClase (idTipoClase, descripcion, numeroMaletaPermitida) values (19, 'Behavior therapy', 9);
insert into aerolinea.TipoClase (idTipoClase, descripcion, numeroMaletaPermitida) values (20, 'Osteoclasis-humerus', 10);
insert into aerolinea.TipoClase (idTipoClase, descripcion, numeroMaletaPermitida) values (21, 'Selective vagotomy NEC', 1);
insert into aerolinea.TipoClase (idTipoClase, descripcion, numeroMaletaPermitida) values (22, 'Packed cell transfusion', 4);
insert into aerolinea.TipoClase (idTipoClase, descripcion, numeroMaletaPermitida) values (23, 'Perc abltn lung les/tiss', 9);
insert into aerolinea.TipoClase (idTipoClase, descripcion, numeroMaletaPermitida) values (24, 'Atrial cardioversion', 1);
insert into aerolinea.TipoClase (idTipoClase, descripcion, numeroMaletaPermitida) values (25, 'Milk extraction', 2);
insert into aerolinea.TipoClase (idTipoClase, descripcion, numeroMaletaPermitida) values (26, 'Closure of tracheostomy', 3);
insert into aerolinea.TipoClase (idTipoClase, descripcion, numeroMaletaPermitida) values (27, 'Psychologic test adminis', 3);
insert into aerolinea.TipoClase (idTipoClase, descripcion, numeroMaletaPermitida) values (28, 'Forceps rotat fetal head', 3);
insert into aerolinea.TipoClase (idTipoClase, descripcion, numeroMaletaPermitida) values (29, 'Other tenotomy', 2);
insert into aerolinea.TipoClase (idTipoClase, descripcion, numeroMaletaPermitida) values (30, 'Delay opening enterostom', 4);
