insert into aerolinea.TipoHallazgo (idTipoHallazgo, descripcion, estado) values (1, 'Swelling in head & neck', 'y');
insert into aerolinea.TipoHallazgo (idTipoHallazgo, descripcion, estado) values (2, 'Disloca midcarpal-closed', 'b');
insert into aerolinea.TipoHallazgo (idTipoHallazgo, descripcion, estado) values (3, 'Pathol dislocat-shlder', 'y');
insert into aerolinea.TipoHallazgo (idTipoHallazgo, descripcion, estado) values (4, 'Nasal bone fx-closed', 'f');
insert into aerolinea.TipoHallazgo (idTipoHallazgo, descripcion, estado) values (5, 'Allrgic gastro & colitis', 'h');
insert into aerolinea.TipoHallazgo (idTipoHallazgo, descripcion, estado) values (6, 'Open wnd nasal cav-compl', 'w');
insert into aerolinea.TipoHallazgo (idTipoHallazgo, descripcion, estado) values (7, 'Ben neo lacrimal duct', 'w');
insert into aerolinea.TipoHallazgo (idTipoHallazgo, descripcion, estado) values (8, 'Outlet contract-antepart', 'l');
insert into aerolinea.TipoHallazgo (idTipoHallazgo, descripcion, estado) values (9, 'Retrobulbar neuritis', 'f');
insert into aerolinea.TipoHallazgo (idTipoHallazgo, descripcion, estado) values (10, '3rd deg brn w loss-scalp', 't');
insert into aerolinea.TipoHallazgo (idTipoHallazgo, descripcion, estado) values (11, 'AMI anterolateral,unspec', 'd');
insert into aerolinea.TipoHallazgo (idTipoHallazgo, descripcion, estado) values (12, 'War inj-unconven war NEC', 'c');
insert into aerolinea.TipoHallazgo (idTipoHallazgo, descripcion, estado) values (13, 'Illeg ab w hemorr-comp', 'j');
insert into aerolinea.TipoHallazgo (idTipoHallazgo, descripcion, estado) values (14, 'Sprain sacrospinatus', 'z');
insert into aerolinea.TipoHallazgo (idTipoHallazgo, descripcion, estado) values (15, 'Fx c1 vertebra-closed', 'y');
insert into aerolinea.TipoHallazgo (idTipoHallazgo, descripcion, estado) values (16, 'Portal hypertension', 'h');
insert into aerolinea.TipoHallazgo (idTipoHallazgo, descripcion, estado) values (17, 'Edema pharynx/nasopharyx', 's');
insert into aerolinea.TipoHallazgo (idTipoHallazgo, descripcion, estado) values (18, 'Disproportion NEC-deliv', 'g');
insert into aerolinea.TipoHallazgo (idTipoHallazgo, descripcion, estado) values (19, 'Lung - kaposi''s sarcoma', 'z');
insert into aerolinea.TipoHallazgo (idTipoHallazgo, descripcion, estado) values (20, 'Uterine size des-antepar', 'q');
insert into aerolinea.TipoHallazgo (idTipoHallazgo, descripcion, estado) values (21, 'Subarach hem-concussion', 'd');
insert into aerolinea.TipoHallazgo (idTipoHallazgo, descripcion, estado) values (22, 'Dislocat knee NOS-open', 'a');
insert into aerolinea.TipoHallazgo (idTipoHallazgo, descripcion, estado) values (23, 'Fx foot bone NEC-open', 'i');
insert into aerolinea.TipoHallazgo (idTipoHallazgo, descripcion, estado) values (24, 'Hepatitis A w/o coma', 'h');
insert into aerolinea.TipoHallazgo (idTipoHallazgo, descripcion, estado) values (25, 'Malig carcinoid jejunum', 'x');
insert into aerolinea.TipoHallazgo (idTipoHallazgo, descripcion, estado) values (26, 'Metatarsus primus varus', 's');
insert into aerolinea.TipoHallazgo (idTipoHallazgo, descripcion, estado) values (27, 'Vertical displace-teeth', 'p');
insert into aerolinea.TipoHallazgo (idTipoHallazgo, descripcion, estado) values (28, 'Thyroid dysfun preg-unsp', 'o');
insert into aerolinea.TipoHallazgo (idTipoHallazgo, descripcion, estado) values (29, 'Cocaine depend-episodic', 'h');
insert into aerolinea.TipoHallazgo (idTipoHallazgo, descripcion, estado) values (30, 'Isol trach tb-exam unkn', 'm');
