insert into aerolinea.Puerta (idPuerta, codigoPuerta, nombre, Terminal_idTerminal) values (1, 'xv-023', 'FluGo', 1);
insert into aerolinea.Puerta (idPuerta, codigoPuerta, nombre, Terminal_idTerminal) values (2, 'qk-212', 'Basil', 2);
insert into aerolinea.Puerta (idPuerta, codigoPuerta, nombre, Terminal_idTerminal) values (3, 'ec-321', 'Pollens - Trees, Beech, American Fagus grandifolia', 3);
insert into aerolinea.Puerta (idPuerta, codigoPuerta, nombre, Terminal_idTerminal) values (4, 'jo-464', 'potassium phosphates', 4);
insert into aerolinea.Puerta (idPuerta, codigoPuerta, nombre, Terminal_idTerminal) values (5, 'tu-507', 'Sulphur Remedy', 5);
insert into aerolinea.Puerta (idPuerta, codigoPuerta, nombre, Terminal_idTerminal) values (6, 'uw-546', 'Motion Sickness Relief', 6);
insert into aerolinea.Puerta (idPuerta, codigoPuerta, nombre, Terminal_idTerminal) values (7, 'oj-360', 'LEVOFLOXACIN', 7);
insert into aerolinea.Puerta (idPuerta, codigoPuerta, nombre, Terminal_idTerminal) values (8, 'ig-930', 'American Beech', 8);
insert into aerolinea.Puerta (idPuerta, codigoPuerta, nombre, Terminal_idTerminal) values (9, 'sa-504', 'Allopurinol', 9);
insert into aerolinea.Puerta (idPuerta, codigoPuerta, nombre, Terminal_idTerminal) values (10, 'ow-059', 'Olanzapine', 10);
insert into aerolinea.Puerta (idPuerta, codigoPuerta, nombre, Terminal_idTerminal) values (11, 'uy-164', 'Sterile Water', 11);
insert into aerolinea.Puerta (idPuerta, codigoPuerta, nombre, Terminal_idTerminal) values (12, 'qe-902', 'Squash Zucchini', 12);
insert into aerolinea.Puerta (idPuerta, codigoPuerta, nombre, Terminal_idTerminal) values (13, 'lq-944', 'Sisal', 13);
insert into aerolinea.Puerta (idPuerta, codigoPuerta, nombre, Terminal_idTerminal) values (14, 'fg-255', 'Starlix', 14);
insert into aerolinea.Puerta (idPuerta, codigoPuerta, nombre, Terminal_idTerminal) values (15, 'dd-377', 'Alder, White Pollen', 15);
insert into aerolinea.Puerta (idPuerta, codigoPuerta, nombre, Terminal_idTerminal) values (16, 'np-017', 'Alprazolam', 16);
insert into aerolinea.Puerta (idPuerta, codigoPuerta, nombre, Terminal_idTerminal) values (17, 'zm-415', 'Lubriderm Intense Skin Repair', 17);
insert into aerolinea.Puerta (idPuerta, codigoPuerta, nombre, Terminal_idTerminal) values (18, 'nl-588', 'Hydrochlorothiazide', 18);
insert into aerolinea.Puerta (idPuerta, codigoPuerta, nombre, Terminal_idTerminal) values (19, 'iz-894', 'POPULUS DELTOIDES POLLEN', 19);
insert into aerolinea.Puerta (idPuerta, codigoPuerta, nombre, Terminal_idTerminal) values (20, 'st-952', 'Diltiazem Hydrochloride', 20);
insert into aerolinea.Puerta (idPuerta, codigoPuerta, nombre, Terminal_idTerminal) values (21, 'ez-720', 'Losartan Potassium', 21);
insert into aerolinea.Puerta (idPuerta, codigoPuerta, nombre, Terminal_idTerminal) values (22, 'xx-717', 'Suave Sweet Pea and Violet', 22);
insert into aerolinea.Puerta (idPuerta, codigoPuerta, nombre, Terminal_idTerminal) values (23, 'mg-419', 'Stool Softener', 23);
insert into aerolinea.Puerta (idPuerta, codigoPuerta, nombre, Terminal_idTerminal) values (24, 'kr-372', 'Prazosin Hydrochloride', 24);
insert into aerolinea.Puerta (idPuerta, codigoPuerta, nombre, Terminal_idTerminal) values (25, 'gr-774', 'Preferred Plus Aller Ease', 25);
insert into aerolinea.Puerta (idPuerta, codigoPuerta, nombre, Terminal_idTerminal) values (26, 'sf-313', 'phendimetrazine tartrate', 26);
insert into aerolinea.Puerta (idPuerta, codigoPuerta, nombre, Terminal_idTerminal) values (27, 'ql-870', 'Eve Lom Radiance Perfected Tinted Moisturiser Broad Spectrum SPF 15 Sunscreen', 27);
insert into aerolinea.Puerta (idPuerta, codigoPuerta, nombre, Terminal_idTerminal) values (28, 'gq-189', 'Carvedilol', 28);
insert into aerolinea.Puerta (idPuerta, codigoPuerta, nombre, Terminal_idTerminal) values (29, 'kq-206', 'METHYLPHENIDATE HYDROCHLORIDE', 29);
insert into aerolinea.Puerta (idPuerta, codigoPuerta, nombre, Terminal_idTerminal) values (30, 'ue-216', 'Chicken Meat', 30);
