insert into aerolinea.FormaPago (idFormaPago, descripcion) values (1, 'Peso');
insert into aerolinea.FormaPago (idFormaPago, descripcion) values (2, 'Franc');
insert into aerolinea.FormaPago (idFormaPago, descripcion) values (3, 'Real');
insert into aerolinea.FormaPago (idFormaPago, descripcion) values (4, 'Zloty');
insert into aerolinea.FormaPago (idFormaPago, descripcion) values (5, 'Peso');
insert into aerolinea.FormaPago (idFormaPago, descripcion) values (6, 'Ruble');
insert into aerolinea.FormaPago (idFormaPago, descripcion) values (7, 'Yuan Renminbi');
insert into aerolinea.FormaPago (idFormaPago, descripcion) values (8, 'Manat');
insert into aerolinea.FormaPago (idFormaPago, descripcion) values (9, 'Euro');
insert into aerolinea.FormaPago (idFormaPago, descripcion) values (10, 'Euro');
insert into aerolinea.FormaPago (idFormaPago, descripcion) values (11, 'Yuan Renminbi');
insert into aerolinea.FormaPago (idFormaPago, descripcion) values (12, 'Denar');
insert into aerolinea.FormaPago (idFormaPago, descripcion) values (13, 'Rupiah');
insert into aerolinea.FormaPago (idFormaPago, descripcion) values (14, 'Yuan Renminbi');
insert into aerolinea.FormaPago (idFormaPago, descripcion) values (15, 'Tugrik');
insert into aerolinea.FormaPago (idFormaPago, descripcion) values (16, 'Peso');
insert into aerolinea.FormaPago (idFormaPago, descripcion) values (17, 'Dollar');
insert into aerolinea.FormaPago (idFormaPago, descripcion) values (18, 'Dollar');
insert into aerolinea.FormaPago (idFormaPago, descripcion) values (19, 'Yuan Renminbi');
insert into aerolinea.FormaPago (idFormaPago, descripcion) values (20, 'Peso');
insert into aerolinea.FormaPago (idFormaPago, descripcion) values (21, 'Peso');
insert into aerolinea.FormaPago (idFormaPago, descripcion) values (22, 'Yuan Renminbi');
insert into aerolinea.FormaPago (idFormaPago, descripcion) values (23, 'Dollar');
insert into aerolinea.FormaPago (idFormaPago, descripcion) values (24, 'Zloty');
insert into aerolinea.FormaPago (idFormaPago, descripcion) values (25, 'Yuan Renminbi');
insert into aerolinea.FormaPago (idFormaPago, descripcion) values (26, 'Yuan Renminbi');
insert into aerolinea.FormaPago (idFormaPago, descripcion) values (27, 'Rial');
insert into aerolinea.FormaPago (idFormaPago, descripcion) values (28, 'Koruna');
insert into aerolinea.FormaPago (idFormaPago, descripcion) values (29, 'Krona');
insert into aerolinea.FormaPago (idFormaPago, descripcion) values (30, 'Yuan Renminbi');
